language: node_js
node_js:
  - 9.8.0
cache:
  directories:
    - node_modules
before_script:
  - npm install codecov.io coveralls
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
script:
  - npm run build
  - node --harmony ./node_modules/.bin/jest --coverage